steps:
  # Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'us-central1-docker.pkg.dev/ramakk-gcp/demo-repo/app1:tag2', '.']

  # Push the Docker image to Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'us-central1-docker.pkg.dev/ramakk-gcp/demo-repo/app1:tag2']

  # Deploy to Cloud Run with specified service account
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      - 'run'
      - 'deploy'
      - 'app1'
      - '--image'
      - 'us-central1-docker.pkg.dev/ramakk-gcp/demo-repo/app1:tag2'
      - '--region'
      - 'us-central1'
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' 
      - '--port'
      - '80'
      - '--service-account'
      - 'cloud-build@ramakk-gcp.iam.gserviceaccount.com'  # Replace with your service account email

images:
  - 'us-central1-docker.pkg.dev/ramakk-gcp/demo-repo/app1:tag2'

options:
  logging: CLOUD_LOGGING_ONLY
