steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'us-central1-docker.pkg.dev/rama17-05-2020/sanjay-repo/app:tag1', '.']

images:
- 'us-central1-docker.pkg.dev/rama17-05-2020/sanjay-repo/app:tag1'

