name: Cloud Build CI/CD

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: nginx-latest

    steps:
    # Checkout the repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up Google Cloud SDK
    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: rama17-05-2020
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    # Configure Docker for Google Cloud
    - name: Configure Docker for Google Cloud
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    # Trigger Cloud Build
    - name: Trigger Cloud Build
      run: gcloud builds submit --config cloudbuild.yaml .
