name: Cloud Build CI/CD

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: nginix-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: rama17-05-2020
        service_account_key: ${{ secrets.GCP_SA_KEY }}

    - name: Configure Docker
      run: gcloud auth configure-docker us-central1-docker.pkg.dev

    - name: Trigger Cloud Build
      run: gcloud builds submit --config cloudbuild.yaml .
